{{- if .Values.client.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name-client" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name-client" . }}
  labels:
    application: {{ template "name-client" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name-client" . }}-{{ $.Values.client.name }}
  labels:
    application: {{ template "name-client" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $.Release.Namespace }}
    name: {{ template "name-client" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "name-client" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "name-client" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
rules:
  # svcs
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - list
      - delete
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - create
      - update
      - list
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name-client" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $.Release.Namespace }}
    name: {{ template "name-client" . }}
roleRef:
  kind: Role
  name: {{ template "name-client" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}