# Those PVCs are used for development, one as golang build cache, one as code storage (synchronized by Tilt)
{{- if .Values.devMode.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "name-client" . }}-build-cache
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
spec:
  {{- if .Values.client.pvc.storageClassName }}
  storageClassName: {{ .Values.client.pvc.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.client.pvc.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "name-client" . }}-code
  namespace: {{ $.Release.Namespace }}
  labels:
    application: {{ template "name-client" . }}
spec:
  {{- if .Values.client.pvc.storageClassName }}
  storageClassName: {{ .Values.client.pvc.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.client.pvc.storage }}
{{- end }}