---
# Source: onprem/charts/platform-operator-rabbitmq/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wormhole-client
  labels:
    application: wormhole-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wormhole-client
  labels:
    application: wormhole-client
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wormhole-client
  labels:
    application: wormhole-client
subjects:
  - kind: ServiceAccount
    namespace: wormhole
    name: wormhole-client
roleRef:
  kind: ClusterRole
  name: wormhole-client
  apiGroup: rbac.authorization.k8s.io