---
# Source: onprem/charts/platform-operator-rabbitmq/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wormhole-server
  labels:
    application: wormhole-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wormhole-server
  labels:
    application: wormhole-server
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wormhole-server
  labels:
    application: wormhole-server
subjects:
  - kind: ServiceAccount
    namespace: wormhole
    name: wormhole-server
roleRef:
  kind: Role
  name: wormhole-server
  apiGroup: rbac.authorization.k8s.io