---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: {name}
  namespace: {namespace}
  name: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: {name}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {name}
    spec:
      containers:
        - image: ghcr.io/glothriel/wormhole:latest
          name: wormhole
          imagePullPolicy: Always
          command:
            - /usr/bin/wormhole
            - testserver
            - --port
            - "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    application: {name}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: {name}
  sessionAffinity: None
  type: ClusterIP
