name: Integration
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.x"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install packages required for tests
        run: uv sync --project tests --no-install-project

      - name: Run integration tests
        run: uv run --project tests pytest -v --tb=short tests/

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install packages required for linting
        run: uv sync --project tests --no-install-project

      - name: Run ruff check
        run: uv run --project tests ruff check .